# Generated by Django 2.1.2 on 2018-12-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminInterface', '0002_auto_20181221_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='pics',
            field=models.ImageField(default='icon/file-not-found.jpg', unique=True, upload_to='topic_image/'),
        ),
    ]
