# Generated by Django 2.1.2 on 2018-12-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminInterface', '0005_auto_20181224_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=4000)),
                ('email', models.CharField(max_length=55)),
                ('resolved', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
